name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      # 2. Start an Nx Cloud CI run (enable task distribution & logging)
      - name: Start Nx Cloud
        run: npx nx-cloud start-ci-run \
             --distribute-on="3 linux-medium-js" \
             --stop-agents-after="e2e-ci"

      # 3. Setup Node & cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 5. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 6. Lint & Build only (skip unit tests)
      - name: Lint & Build
        run: npx nx affected --target=lint --target=build

      # 7. Run your E2E suite in headed mode under Xvfb
      - name: Run E2E (via Nx)
        run: |
          npm run start &
          npx wait-on http://localhost:4200
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
            npx nx run military-dog-e2e:e2e --ci --parallel=1 --reporter=github


      # 8. Stop the Nx Cloud run (optional, on completion)
      - name: Stop Nx Cloud
        if: always()
        run: npx nx-cloud stop-ci-run
