name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-depsname: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      # 2. Start Nx Cloud for distributed caching
      - name: Start Nx Cloud
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 4. Install deps
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 5. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 6. Record SHAs (for Nx Cloud)
      - name: Record SHAs for Nx Cloud
        uses: nrwl/nx-set-shas@v4

      # 7. Lint, Build & E2E only (no unit tests)
      - name: Lint, Build & E2E
        run: |
          # --all makes sure it runs even if no files appear "affected"
          npx nx affected \
            --target=lint \
            --target=build \
            --target=e2e \
            --all

      # 8. Stop Nx Cloud run
      - name: Stop Nx Cloud
        if: always()
        run: npx nx-cloud stop-ci-run

      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: npx nx affected -t lint test build e2e
